### ISSUE TITLE
“Area Map” displays incorrect information

### ISSUE THREAD

**Issue by Lzw104522773** [Gibberlings3/EET#125]
When I finished EET installation，I opened the game,I clicked the "world Map" menu from left side or press M key from keyboard, the game display  “Area Map”,but The location that should have been shown as “Area Map”, it is shown “I gotta say, <CHARNAME>, I really appreciates you bribing me back onna street. Don't like them closed-in places one bit. You're okay in my books, you are. Keep the work up good.”

I tried to install EET use English and Chinese, and it was all the above problems。I think it maybe a bug.As shown in the attached picture：
![6D3D581A00E47D7416FA98DF09486AAC](https://github.com/Gibberlings3/EET/assets/149546927/7996184e-7765-411e-9768-6e3ca98bfa4a)

**Comment by Lzw104522773** [comment]
“I gotta say, , I really appreciates you bribing me back onna street. Don't like them closed-in places one bit. You're okay in my books, you are. Keep the work up good.” is Entry 32898 in BG2EE tlk file(english and chinese)

**Comment by GraionDilach** [comment]
Is that EET_GUI?

**Comment by Lzw104522773** [comment]
> Is that EET_GUI?

Yes,you're right.If I don‘t intall EET_GUI,the above problem will not appear。
