### ISSUE TITLE
[Documentation / FAQ] Can we play Siege of Dragonspear and BG2EE only?

### ISSUE THREAD

**Issue by rubyFeedback** [Gibberlings3/EET#154]
Could a FAQ be added? Right now there is little information on github or the wiki.

I am considering installing EET but I want to only play Siege of Dragonspear and then BG2EE, of course
with many mods pertaining to these two games.

Is that possible in EET? Could this be mentioned in a FAQ too?

**Comment by MephistoSatanDevil** [comment]
You can use the 'Select Campaign' button to choose the 'Siege of Dragon Spear' campaign and start a new game from the beginning of the 'Siege of Dragon Spear'.
