### ISSUE TITLE
Error installing - System_Arch Issue

### ISSUE THREAD

**Issue by Gab74M** [Gibberlings3/EET#35]
Hi. this is the error that appears when trying to install

WeiDU v 24600 Log

 C:\Baldur\Baldur's Gate II Enhanced Edition\Data\00783\setup-EET.exe
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\engine.lua] loaded, 104 bytes
[.\weidu.conf] loaded, 17 bytes
[.\lang\es_es\dialog.tlk] loaded, 12490897 bytes
[.\lang\es_es\dialog.tlk] 103241 string entries
[.\lang\es_es\dialogf.tlk] loaded, 12493971 bytes
[.\lang\es_es\dialogf.tlk] 103241 string entries

Choose your language:
 0 [English]
 1 [Polski (Polish)]
 2 [Spanish]
Using Language [Spanish]
[Spanish] has 6 top-level TRA files
[EET/lang/es_ES/prompts.tra] has 56 translation strings
[EET/lang/es_ES/setup.tra] has 14 translation strings
[EET/lang/es_ES/chapters.tra] has 95 translation strings
[EET/lang/es_ES/dialog.tra] has 37 translation strings
[EET/lang/es_ES/2da.tra] has 55 translation strings
[EET/lang/es_ES/compatibility.tra] has 11 translation strings

Usando .\lang\es_es\dialog.tlk y .\lang\es_es\dialogf.tlk

Quieres que se muestre el readme? [Y]Si, [N]No. 

Instalar Componente [EET core - resource importation]?
[I]Instalar, [N]No Instalar o [Q]Salir. 
Instalando [EET core - resource importation] [1.0 RC11]

INTERACTIVE = 1

LANGUAGE = es_ES

argv[0] = %argv[0]%

argv[1] = %argv[1]%
Copying and patching 1 file ...
[weidu.conf] loaded, 17 bytes

LANGUAGE_BG2 = es_ES
Creating 1 directory
Copying 1 file ...
Copying and patching 2 files ...
[EET/other/cpmvars/eet_cpmvars.tpa] loaded, 59981 bytes
[EET/other/EET_functions.tph] loaded, 43188 bytes
Copying and patching 1 file ...
[EET/bgee_dir.txt] loaded, 62 bytes

C:/Program Files/Baldur's Gate Siege of Dragonspear/Data/00806 directory assigned via EET/bgee_dir.txt

Introduce la ruta completa a tu instalacion de BG:EE+SoD y luego pulsa Intro.
Ejemplo: C:\Program Files (x86)\BeamDog\Games\00806
User answer: "C:\Baldur\Baldur's Gate Siege of Dragonspear\Data\00806"

BG:EE directory used for this installation:
C:/Baldur/Baldur's Gate Siege of Dragonspear/Data/00806
Copying and patching 1 file ...
Copied [.../bgee_dir.txt] to [EET/bgee_dir.txt] (NO BACKUP MADE!)
Copying and patching 1 file ...
[C:/Baldur/Baldur's Gate Siege of Dragonspear/Data/00806/weidu.conf] loaded, 17 bytes

LANGUAGE_BG1 = es_ES
Copying and patching 1 file ...
[C:/Baldur/Baldur's Gate Siege of Dragonspear/Data/00806/WeiDU.log] loaded, 1805 bytes
Copied [C:/Baldur/Baldur's Gate Siege of Dragonspear/Data/00806/WeiDU.log] to [WeiDU-BGEE.log]
Copying 1 file ...
Copied [.../arch_var.bat] to [arch_var.bat]
[arch_var.txt] loaded, 6 bytes
Stopping installation because of error.

ERROR Instalando [EET core - resource importation], revirtiendo a estado anterior
Unable to Unlink [EET/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "EET/backup/0/OTHER.0")
[EET/backup/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   2 files for [EET/EET.TP2] component 0.
Uninstalled      2 files for [EET/EET.TP2] component 0.
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
[.\chitin.key] loaded, 877618 bytes
[.\chitin.key] 189 BIFFs, 62285 resources
Unable to Unlink [EET/backup/0/READLN.0]: Unix.Unix_error(20, "unlink", "EET/backup/0/READLN.0")
Unable to Unlink [EET/backup/0/READLN.0.TEXT]: Unix.Unix_error(20, "unlink", "EET/backup/0/READLN.0.TEXT")
ERROR: Failure("Uninitialised return value: SYSTEM_ARCH")
Por favor, envia el archivo SETUP-EET.DEBUG a K4thos (swit)
Using Language [Spanish]
[Spanish] has 6 top-level TRA files
[EET/lang/es_ES/prompts.tra] has 56 translation strings
[EET/lang/es_ES/setup.tra] has 14 translation strings
[EET/lang/es_ES/chapters.tra] has 95 translation strings
[EET/lang/es_ES/dialog.tra] has 37 translation strings
[EET/lang/es_ES/2da.tra] has 55 translation strings
[EET/lang/es_ES/compatibility.tra] has 11 translation strings

Instalar Componente [EET core - resource importation]?
[I]Instalar, [N]No Instalar o [Q]Salir. Saving This Log:

NO INSTALADO DEBIDO A ERRORES EET core - resource importation

		WeiDU Timings
OUTER_INNER_PATCH_SAVE           0.000
parsing .tra files               0.000
<<<<<<<<                         0.000
OUTER_WHILE                      0.000
ACTION_MATCH                     0.000
adding translation strings       0.000
DELETE                           0.000
load TLK                         0.000
tp2 uninstall                    0.000
DEFINE_PATCH_FUNCTION            0.000
ACTION_READLN                    0.000
DEFINE_ACTION_FUNCTION           0.000
OUTER_SPRINT                     0.000
OUTER_SET                        0.000
INCLUDE                          0.000
BUT_ONLY                         0.000
MKDIR                            0.000
ACTION_DEFINE_ASSOCIATIVE_ARRAY   0.000
ACTION_PHP_EACH                  0.000
parsing .log files               0.000
AT_NOW                           0.000
AT_EXIT                          0.000
function overhead                0.000
DEFINE_ACTION_MACRO              0.000
OUTER_INNER_PATCH                0.000
ACTION_IF                        0.000
PRINT                            0.000
READ_*                           0.000
LAUNCH_ACTION_FUNCTION           0.000
saving files                     0.000
DEFINE_PATCH_MACRO               0.000
COPY                             0.000
eval_pe                          0.016
loading files                    0.016
Parsing TP2 files                0.047
stuff not covered elsewhere      0.047
process_patch2                   0.219
Parsing TPA files                0.219
unmarshal TLK                    0.453
unmarshal KEY                    5.625
TOTAL                            6.641
Executing: [rmdir /s /q EET\temp]

Thank You

**Comment by RoxanneSHS** [comment]
Does EET work on windows XP 32bit?
Of course with using the 32 bit setup weidu exe.
