### ISSUE TITLE
Worldmap vs Sandrah Areas

### ISSUE THREAD

**Issue by RoxanneSHS** [Gibberlings3/EET#41]
Currently Sandrah Saga requires the use of BP_BGT Worldmap instead of EET worldmap and it enforces the use of the very large worldmap for two reasons
1. Waterdeep is "folded" away on the EET worldmap
2. Most new areas are east outside the range of the EET worldmap which aims at N-S extension rather than W-E.

New IWD-in-EET worldmap may remove issue 1 while 2 remains, maybe can be worked around with an insert?

Here  https://www.dropbox.com/s/36uv6pzp5uk26rv/WORLDMAP_SandrahAreas.jpg?dl=1  is the current large worldmap with all Sandrah areas marked in red. Note that the CtB/Sandrah use of the Stormhorn Mountains area is special. It is added to the worldmap by either mod >>> Sandrah checks for CtB and uses/mods the existing area if present, otherwise it will add the area as well and put it to the worldmap. So even with both mods installed there will only be one worldmap entry for that area.

**Comment by K4thos** [comment]
Thanks for the reference map. So it looks like Tantras and Bezantur are outside the scope of the new map. Probably not worth to release it if it doesn't cover all mods :(

**Comment by RoxanneSHS** [comment]
Those areas appear only in the post-ToB part of my mod when you revisit Faerun with new adventures in old and new areas. 
How many players make it to ToB end? How many continue even after that? If those few that play IWD-in-EET plus the extended Sandrah Saga find 2 areas just on the eastern edge of the worldmap, would someone really care?

**Comment by ALIENQuake** [comment]
@RoxanneSHS Can you simply move those two areas so the new map will cover them also?

**Comment by RoxanneSHS** [comment]
@ALIENQuake 
Question - is the new worldmap the only one available or will there be choice to use the new one or BP_GBT worldmap? How to configure those maps to serve both?
