### ISSUE TITLE
EE Mod Setup Fails to Install

### ISSUE THREAD

**Issue by ramboingchris** [Gibberlings3/EET#58]
The EE Mod Setup constantly fails to install with the error below. I am using a Steam version of BG1/2 Enhanced Editions that I have copy/pasted from their respective SteamApps folders to my D drive. I have turned off Windows Defender, UAC, and have given every account I can think of "Full Access" control to the D drive. Using Windows 10, 64-bit.

`'EET.flag' file is used by WeiDU to recognize the installation as EET
Copying 1 file ...
Copying 1 file ...
Copying 1 file ...
'reg' is not recognized as an internal or external command,
operable program or batch file.
Copying and patching 1 file ...
Copying 1 file ...
'cscript' is not recognized as an internal or external command,
operable program or batch file.
Copying 1 file ...
ERROR: error loading [EET/temp/EET.lnk]
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [EET core (resource importation)], rolling back to previous state
Will uninstall 14816 files for [EET/EET.TP2] component 0.
Uninstalled    14816 files for [EET/EET.TP2] component 0.
ERROR: Unix.Unix_error(20, "stat", "EET/temp/EET.lnk")
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Automatically Skipping [EET core (resource importation)] because of error.
Using Language [English]
[.\lang\en_us\dialog.tlk] created, 299738 string entries

NOT INSTALLED DUE TO ERRORS EET core (resource importation)

D:\BALDURS GATE\Baldur's Gate II Enhanced Edition>
ERROR: error loading [EET/temp/EET.lnk]
ERROR: Unix.Unix_error(20, "stat", "EET/temp/EET.lnk")
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.

Without this component the installation cannot be continued.

You can try to repair the problem and install the component again afterwards. In this case please select "retry" after the repair.

If you don't want to spend time on that now, you can also exit the program.
Enter [r]etry or [e]xit.`

**Comment by ALIENQuake** [comment]
@ramboingchris From the error log:
```
'reg' is not recognized as an internal or external command,
operable program or batch file.
'cscript' is not recognized as an internal or external command,
operable program or batch file.
```
Your system has disabled launching VBS scripts and REG command-line tool.

**Comment by K4thos** [comment]
closing since the problem seems to be not in EET code
