### ISSUE TITLE
A message from Russian modders

### ISSUE THREAD

**Issue by RoxanneSHS** [Gibberlings3/EET#63]
I received this message from the Russian community, I just relay it for your consideration:

Here are our edits for the EET that should be added:
in file EET\tbl\compatibility.tbl, so that there is no error with russification, was added
BGEETEXTPACK 0 //RUS BG1
SODRUS 0 //RUS SOD
 
In eet_end.tp2 we added this:
LANGUAGE ~Russian~
~ru_RU~
~EET/lang/ru_RU/prompts.tra~
~EET/lang/ru_RU/setup.tra~
 
Weidu.exe replaced by version 247
And all russian tra files are edited to Si1ver terms.
 
About tipun's edits - here's a quote from him, maybe he changed something else...
About the Disabled:
//SoD Areas
@BD4000 = "<Invalid###Strref####444154>"
@BD1000 = "<Invalid###Strref####444151>"
@BD2000 = "<Invalid###Strref#####444152>"
@BD3000 = "<Invalid###Strref#####444153>"
@BD5000 = "<Invalid###Strref#####444155>"
@BD0010 = "<Invalid###Strref#####444156>"
@BD7000 = "<Invalid###Strref####458679>"
@BD7100 = "<Invalid###Strref#####458680>"
@BD7200 = "<Invalid###Strref#####458681>"
@BD7300 = "<Invalid###Strref#####458682>"
@BD7400 = "<Invalid###Strref####458683>"
The error is in the file EET\lib\macros.tph.
 
There you must replace near line 461:
LPF EET_strref INT_VAR str = name add = strrefAdd RET str END
to
LPF EET_strref INT_VAR str = name RET str END.
 
And around line 467:
LPF EET_strref INT_VAR str = tool add = strrefAdd RET str END
to
LPF EET_strref INT_VAR str = tool RET str END.
 
That is, in two places remove add = strrefAdd.

**Comment by K4thos** [comment]
all solved, thanks
