### ISSUE TITLE
BG1NPC Music Causes Install Failure.

### ISSUE THREAD

**Issue by Communard1871** [Gibberlings3/EET#65]
New update causes install failure when BG1NPC music pack is installed on BG:EE, but BG1NPC itself is not (which is the install order recommended by the EET Compatibility List). Deleting the BG1NPC Music Pack line from the BGEE WeiDU.log allowed install to proceed, have not yet tested to see if this causes any issues with mod function.

My non-expert guess is that this is caused by updated syntax in the "EET/compat/bg1npc/include.tph" file, which I see has been changed when versions are compared.

[ProjectInfinity-Weidu-Debug-EET-0-Error.log](https://github.com/Gibberlings3/EET/files/6707503/ProjectInfinity-Weidu-Debug-EET-0-Error.log)

**Comment by K4thos** [comment]
recommended installation order for both BG1NPC and Music Pack is after EET installation, not on BG:EE. More details: https://www.gibberlings3.net/forums/topic/27741-mod-compatibility-list-for-eet/?do=findComment&comment=295891

**Comment by K4thos** [comment]
the error you've mentioned is unrelated to BG1NPC Music. It was fixed in this commit: https://github.com/Gibberlings3/EET/commit/cb7414d951bc13638a5b0e4a242d2132738c485f
(will be included in v13.1 release)
Thanks for reporting.
