### ISSUE TITLE
Fail to install EET windows 10

### ISSUE THREAD

**Issue by Rataxor** [Gibberlings3/EET#76]
Here the bug report :

ERREUR pendant l'installation de [EET core (importation de ressource)], retour a l'etat anterieur
Will uninstall 14695 files for [EET/EET.TP2] component 0.
Problem Unix.Unix_error(1, "mkdir", "C:") on C:: util.ml
Problem Unix.Unix_error(1, "mkdir", "C:/Users/F\130f\130") on C:/Users/Féfé: util.ml
Uninstalled    14695 files for [EET/EET.TP2] component 0.
ERROR: Sys_error("C:\\Users\\F\130f\130\\Desktop: No such file or directory")
S'IL VOUS PLAIT, envoyez par e-mail le fichier SETUP-EET.DEBUG a K4thos (swit)
Using Language [French]

Thanks for all the work !

**Comment by Rataxor** [comment]
I succes to change the name of the user folder (it's not so easy as right clic > rename, i had to create a new admin acount and dive into the register bla bla bla ^^)

Anyway, after rename Féfé into Fefe, I retryed to instal EET and it works !

**Comment by GraionDilach** [comment]
EET might be shipped with an older WeiDU version, but using the x64 version of v249 should have handled this properly as far as I'm aware.
