### ISSUE TITLE
fail to install for VALERIE BG:EE mod is not recognized by EET

### ISSUE THREAD

**Issue by ccharname** [Gibberlings3/EET#80]
hello everyone , i try to install eet with ee-mod-setup-tool, but failure mant times
according to the log, it's because the pre-install mods on bgee, like below
should i just remove those mods?

FAILURE:
VALERIE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET
ERROR: [D:/SteamLibrary/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] -> [EET/temp/WeiDU.log] Patching Failed (COPY) (Failure("VALERIE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET"))
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [EET core (resource importation)], rolling back to previous state
Will uninstall   1 files for [EET/EET.TP2] component 0.
Uninstalled      1 files for [EET/EET.TP2] component 0.
ERROR: Failure("VALERIE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET")
PLEASE email the file SETUP-EET.DEBUG to K4thos (swit)
Automatically Skipping [EET core (resource importation)] because of error.
Using Language [English]

NOT INSTALLED DUE TO ERRORS EET core (resource importation)

D:\SteamLibrary\steamapps\common\Baldur's Gate II Enhanced Edition>
ERROR: [D:/SteamLibrary/steamapps/common/Baldur's Gate Enhanced Edition/WeiDU.log] -> [EET/temp/WeiDU.log] Patching Failed (COPY) (Failure("VALERIE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET"))
ERROR: Failure("VALERIE BG:EE mod is not recognized by EET, so it can't be imported to BG2:EE with EET")
Enhanced Edition Trilogy (Enhanced Edition Trilogy) was not installed due to errors.

Without this component the installation cannot be continued.

**Comment by GraionDilach** [comment]
I presume EET Mod Messup offers a wrong version of Valerie because I know I have managed to install the last official version of the mod to BGEE prior to EET multiple times. What EET Mod Messup is doing s beyond the control of the community.

**Comment by mleduque** [comment]
Valerie is advertised as EET compatible and should work installed after EET.
At least that how I installed it last time I did.

https://github.com/SpellholdStudios/Valerie_NPC/releases/tag/v1.2

I see no compat entry for valerie in EET there
http://www.shsforums.net/forum/617-valerie/
